### ISSUE TITLE
Configure Backup Routine

### ISSUE THREAD

**Issue by abelpink** [PEDSnet/PEDSpace#45]
To be completed after the production instance is finished.

Need a system to schedule regular backups of the system. This will be important for tracking versioning and in case we ever need to recover a previous version. Assigning @shorrocka because @aseyedia doesn't have access to the VM panels.

**Comment by aseyedia** [comment]
I spoke with @shorrocka and he's telling me that it would probably be way easier to just perform server-side backups periodically and maybe even deposit them to Isilon. Migrating to AWS is potentially more hassle than it's worth.

**Comment by aseyedia** [comment]
I created and added a backup routine to `crontab` that archives the Postgres database and the `assetstore/` directory in the `dspace` folder to `/data/backups` and also archives to `/mnt/isilon/pedsnet/DSpace/PEDSpace/`. Here is our default backup policy:

- Backups occur every day at 2 am.
- Backups are held for 30 days on `/data/backups`.
- Backups are held for 90 days on `/mnt/isilon/pedsnet/DSpace/PEDSpace`.

You can change these policies, but you have to call `sudo crontab -e` from my account (`seyediana1`). If/when I leave PEDSnet or this project is handed off to someone else (or both), these `crontab` settings **must** happen under someone else's user account.

**Comment by aseyedia** [comment]
Oh, forgot to add: in order for this to work, the Postgres credentials **need to be** stored under `~/.pgpass`. 

```
localhost:5432:dspace:dspace:[add dspace password here]
```

This allows the `crontab` scheduler to execute tasks involving a Postgres connection without requiring human input.
