### ISSUE TITLE
Embed content on DQ Check Record Pages

### ISSUE THREAD

**Issue by abelpink** [PEDSnet/PEDSpace#55]
There is interest from the SSDQA team in embedding some content into the Simple Item View pages of the Data Quality Checks. This would include an html graph (to appear beneath the Visualization field) and a csv file (to appear beneath the Raw Output field). 

I'd like to know if this is logistically possible, and approximately how long it would take to configure something like this. 

Let me know if you'd like some example content to experiment with.

Thanks!

**Comment by aseyedia** [comment]
Our options are either making the image in question the thumbnail or using the [Mirador Viewer](https://mirador-dev.netlify.app/__tests__/integration/mirador/) in conjunction with [IIIF](https://wiki.lyrasis.org/display/DSDOC8x/IIIF+Configuration#IIIFConfiguration-Overview).

**Comment by aseyedia** [comment]
doesn't seem like too much. there's a documentation page for it.
