### ISSUE TITLE
Phenotype item edit is not loading dc_subject.xml

### ISSUE THREAD

**Issue by abelpink** [PEDSnet/PEDSpace#61]
The dc.subject field is loading srsc.xml rather than dc_subject.xml in the item edit metadata form. It is pulling from the correct vocabulary in the item submission form, but not the item editor.

**Comment by aseyedia** [comment]
We learned that the collection for a DSpace object has to have a corresponding entity type for the "edit item" submission form vocabularies to work, for some reason, and it won't change afterwards.
