### ISSUE TITLE
System Wide Alert won't stick.

### ISSUE THREAD

**Issue by abelpink** [PEDSnet/PEDSpace#67]
I'm trying to use the "system wide alert" feature in the Admin menu to add the warning "Please Note: PEDSpace is currently under construction," but it disappears as soon as I log out. When I log in and go back to the feature it says that it's active?

**Comment by aseyedia** [comment]
Freshly closed issue here https://github.com/DSpace/dspace-angular/issues/3424, expect it in a forth-coming DSpace release.
