### ISSUE TITLE
Write script duplicating tag (dc.subject) metadata

### ISSUE THREAD

**Issue by abelpink** [PEDSnet/PEDSpace#71]
We want to provide users with the ability to browse record tags in two ways: using the term hierarchy, and via a flat list ordered by occurrence. To do this, we need two different fields - one that is linked to the term hierarchy, and one that is uncontrolled - containing identical information.

The metadata fields corresponding to these needs are:
`dc.subject` : Hierarchical/Controlled, linked to `dc_subject.xml`
`local.subject.flat` : Flat/Uncontrolled

When a record is created using the submission form, the user should only apply one set of tags, all using the `dc.subject` entry corresponding to the controlled vocabulary. 

We want to write a script that operates on the postgres database which copies the data applied to the `dc.subject` field(s) and pastes it into `local.subject.flat` field(s). The nodes of the hierarchy will need to be removed, i.e., only the characters following the last "::" should be copied. 

This means that future submissions tagging will automatically populate the `local.subject.flat` field, and that the two filters will be able to be used in their respective manners.

**Comment by aseyedia** [comment]
In order for me to progress on this issue, I will need to first synchronize the DSpace instances - PSQL and bitstreams. It's not strictly necessary but it makes testing more effective, since, I don't think `local.subject.flat` is in the development server, and in general there are other things that will probably make testing easier.

**Comment by aseyedia** [comment]
Wrote a curation task [here](https://github.com/PEDSnet/PEDSpace/blob/main/config/CopyHierarchicalSubjectsToFlat.java) that automatically takes care of this during submission.

- 36db4d32d5cf9461e38754691fb31b09244a6e78
- b44dfb1c03d447500a34fff815ce6c2544ec8943
- 6d5db9bc19e67b943b3ce5a3eec23b86406db523
- 8d0b951929e31eb6f5038896cf70aa09e75e5c68
- 6612084b3c162ad25e0d89c1404b7793c59e58e6
- 736f2f0ad0b31aa2f453055639c23ff196c036ed
- ba903f8f7160eddb41b0691b57aeefbd72b9effd
- 1aeff26101fa1bce268bed4159b420a096c1bbb4
- 4f3877a9b5c785d03ab528bf6c157731aaa0c220

Also found an open source contribution here: 310adee13e6864a32aa71408d876726d50a58059 (still no such translation exists on [the upstream HEAD](https://github.com/DSpace/dspace-angular/blob/main/src/assets/i18n/en.json5), but it's Christmas Eve and I don't want to deal with it right now).
