### ISSUE TITLE
Remove Underline from Filter menu items

### ISSUE THREAD

**Issue by abelpink** [PEDSnet/PEDSpace#73]
As Charlie pointed out in a previous Thursday meeting, the underlined options in the filter menu option make them look like links, when really the user should just be checking the boxes. Could we remove the underline from those? Only if it's not too hard - this is low priority.

**Comment by aseyedia** [comment]
Oops, typo in the commit message. 

Here's the commit that fixed it: https://github.com/PEDSnet/PEDSpace/commit/224d49c18335fbf6cb8640c2c12ff010e9805a21
